{ config, inputs, ... }:
{
  flake.modules.nixos.grim =
    {
      imports = [
        inputs.agenix.nixosModules.default
      ];
      
      age.secrets.github-key = {
        file = ./secrets/github.com.age;
        mode = "0600";
        owner = "root";
      };
      
      environment.etc."ssh/ssh_config.d/github.com-identity.conf" = {
        text = ''
          # Generated by gitSshConfig module
          Host github.com
              User git
              IdentityFile "${config.age.secrets.github-key.path}"
        '';
        mode = "0644";  # Readable by all users
      };

      programs.ssh.extraConfig = "Include /etc/ssh/ssh_config.d/github.com-identity.conf";
    };
}
