{ config, lib, pkgs, ... }:

with lib;

let
  cfg = config.services.githubSshConfig;
in
{
  options.services.githubSshConfig = {
    enable = mkEnableOption "system-wide SSH config with agenix secret";
    
    identityFile = mkOption {
      type = types.path;
      description = "Path to the agenix secret for SSH identity";
      example = literalExpression "config.age.secrets.ssh-key.path";
    };
  };
  
  config = mkIf cfg.enable {
    environment.etc."ssh/ssh_config.d/50-agenix-identity.conf" = {
      text = ''
        # Generated by githubSshConfig module
        Host github.com
            User git
            IdentityFile ${cfg.identityFile}
      '';
      mode = "0644";  # Readable by all users
    };

    programs.ssh.extraConfig =''
      Include /etc/ssh/ssh_config.d/50-agenix-identity.conf
    '';
  };
}
